# For more info on HTTP files go to https://aka.ms/vs/httpfile

POST https://localhost:7076/api/postales/getfelicitacion
Content-Type: application/json

{
  "anyo": 2023,
  "intervals": {
    "intervals": [      
    ]
  }
}

###

POST https://localhost:7076/api/postales/getfelicitacion
Content-Type: application/json

{
  "anyo": 2023,
  "intervals": {
    "intervals": [
      {
        "start": 1,
        "end": 1
      }
    ]
  }
}

###

POST http://microbykonamic.es/api/postales/getfelicitacion
Content-Type: application/json

{
  "anyo": 2023,
  "intervals": {
    "intervals": [      
    ]
  }
}

###