// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroBytKonamic.Data.Entities;

public partial class Fortunesofday
{
    public int IdfortunesOfDay { get; set; }

    public DateTime Day { get; set; }

    public int IdLanguages { get; set; }

    public int IdFortunes { get; set; }

    public virtual Fortune IdFortunesNavigation { get; set; }

    public virtual Language IdLanguagesNavigation { get; set; }
}