// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroBytKonamic.Data.Entities;

public partial class Fortune
{
    public int IdFortunes { get; set; }

    public int IdFilesFortunes { get; set; }

    public string Fortune1 { get; set; }

    public virtual Filesfortune IdFilesFortunesNavigation { get; set; }
}